DROP SCHEMA IF EXISTS maintenance;
DROP SCHEMA IF EXISTS security;
DROP SCHEMA IF EXISTS notification;
DROP SCHEMA IF EXISTS billing;
DROP SCHEMA IF EXISTS inventory;
DROP SCHEMA IF EXISTS service_delivery;
DROP SCHEMA IF EXISTS distribution;
DROP SCHEMA IF EXISTS configuration;


