DROP SCHEMA IF EXISTS mantenimiento CASCADE;
DROP SCHEMA IF EXISTS seguridad CASCADE;
DROP SCHEMA IF EXISTS notificacion CASCADE;
DROP SCHEMA IF EXISTS inventario CASCADE;
DROP SCHEMA IF EXISTS facturacion CASCADE;
DROP SCHEMA IF EXISTS prestacion_servicio CASCADE;
DROP SCHEMA IF EXISTS distribucion CASCADE;
DROP SCHEMA IF EXISTS parametrizacion CASCADE;
