DELETE FROM maintenance.maintenance_dashboard;
DELETE FROM notification.customer_loyalty;
DELETE FROM notification.term_condition WHERE version = 'v1.0.0';
DELETE FROM billing.partial_payment WHERE payment_reference = 'ABONO-DEMO-001';
DELETE FROM billing.pre_invoice;
DELETE FROM service_delivery.stay;
DELETE FROM service_delivery.room_reservationtion;
DELETE FROM inventory.inventory_availability;
DELETE FROM inventory.service WHERE name IN ('Lavanderia', 'Desayuno', 'Parqueadero');
DELETE FROM inventory.product WHERE name = 'Agua mineral';
DELETE FROM inventory.supplier WHERE nit = '800000000-1';
DELETE FROM configuration.price;
DELETE FROM distribution.room_catalog;
DELETE FROM distribution.room WHERE number IN ('101', '201');
DELETE FROM distribution.site WHERE name = 'Sede Principal';
DELETE FROM distribution.room_status WHERE name IN ('AVAILABLE', 'RESERVED', 'OCCUPIED', 'CLEANING', 'BLOCKED', 'MAINTENANCE');
DELETE FROM distribution.room_type WHERE name IN ('SINGLE', 'DOUBLE', 'SUITE');
DELETE FROM security.rolee_permission;
DELETE FROM security.user_rolee;
DELETE FROM security.user_account WHERE username = 'ariel5253';
DELETE FROM security.module;
DELETE FROM security.permission;
DELETE FROM security.role;
DELETE FROM configuration.employee;
DELETE FROM configuration.person WHERE document_number IN ('52530001', '52530002');
DELETE FROM configuration.customer WHERE document_number IN ('100000001', '100000002');
DELETE FROM configuration.payment_method WHERE name IN ('CASH', 'CARD', 'BANK_TRANSFER');
DELETE FROM configuration.day_type WHERE name IN ('WEEKDAY', 'WEEKEND', 'HOLIDAY', 'HIGH_SEASON');
DELETE FROM configuration.company WHERE nit = '900000000-1';


