DELETE FROM mantenimiento.dashboard_mantenimiento;
DELETE FROM notificacion.fidelizacion_cliente;
DELETE FROM notificacion.termino_condicion WHERE version = 'v1.0.0';
DELETE FROM facturacion.pago_parcial WHERE referencia_pago = 'ABONO-DEMO-001';
DELETE FROM facturacion.pre_factura;
DELETE FROM prestacion_servicio.estadia;
DELETE FROM prestacion_servicio.reserva_habitacion;
DELETE FROM inventario.disponibilidad_inventario;
DELETE FROM inventario.servicio WHERE nombre IN ('Lavanderia', 'Desayuno', 'Parqueadero');
DELETE FROM inventario.producto WHERE nombre = 'Agua mineral';
DELETE FROM inventario.proveedor WHERE nit = '800000000-1';
DELETE FROM parametrizacion.precio;
DELETE FROM distribucion.catalogo_habitacion;
DELETE FROM distribucion.habitacion WHERE numero IN ('101', '201');
DELETE FROM distribucion.sede WHERE nombre = 'Sede Principal';
DELETE FROM distribucion.estado_habitacion WHERE nombre IN ('DISPONIBLE', 'RESERVADA', 'OCUPADA', 'LIMPIEZA', 'BLOQUEADA', 'MANTENIMIENTO');
DELETE FROM distribucion.tipo_habitacion WHERE nombre IN ('SENCILLA', 'DOBLE', 'SUITE');
DELETE FROM seguridad.rol_permiso;
DELETE FROM seguridad.usuario_rol;
DELETE FROM seguridad.usuario WHERE username = 'ariel5253';
DELETE FROM seguridad.modulo;
DELETE FROM seguridad.permiso;
DELETE FROM seguridad.rol;
DELETE FROM parametrizacion.empleado;
DELETE FROM parametrizacion.persona WHERE numero_documento IN ('52530001', '52530002');
DELETE FROM parametrizacion.cliente WHERE numero_documento IN ('100000001', '100000002');
DELETE FROM parametrizacion.metodo_pago WHERE nombre IN ('EFECTIVO', 'TARJETA', 'TRANSFERENCIA');
DELETE FROM parametrizacion.tipo_dia WHERE nombre IN ('ENTRE_SEMANA', 'FIN_SEMANA', 'FERIADO', 'TEMPORADA_ALTA');
DELETE FROM parametrizacion.empresa WHERE nit = '900000000-1';
