CREATE SCHEMA IF NOT EXISTS parametrizacion;
CREATE SCHEMA IF NOT EXISTS distribucion;
CREATE SCHEMA IF NOT EXISTS prestacion_servicio;
CREATE SCHEMA IF NOT EXISTS facturacion;
CREATE SCHEMA IF NOT EXISTS inventario;
CREATE SCHEMA IF NOT EXISTS notificacion;
CREATE SCHEMA IF NOT EXISTS seguridad;
CREATE SCHEMA IF NOT EXISTS mantenimiento;

